project:
  type: website
  output-dir: docs
  
execute: 
  freeze: auto

website:
  title: "Open Research Project Living Website Demo"
  site-url: https://UKRN.github.io/OR-demo
  repo-url: https://github.com/UKRN/OR-demo
  image: images/logo.png
  favicon: images/favicon.ico
  navbar:
    logo: /images/logo.png
    logo-alt: "Globe with UKRN and big pink UK"
    right:
      - about.qmd
      - text: Projects
        menu: 
          - projects/training.qmd
          - projects/evaluation.qmd
          - projects/sharing.qmd
          - projects/management.qmd
          - projects/recognition.qmd
          - projects/dei.qmd
      - news.qmd
      - demo.qmd
  sidebar:
    - title: "Style Guide"
      alignment: right
      contents:
        - text: UKRN
          href: ukrn.org
  page-footer:
    background: primary
    right:
      - text: credit
        href: credit.html
      - text: "{{< ai osf size=1x >}}"
        aria-label: OSF
        href: https://osf.io/x8j9q/
      - icon: github
        aria-label: GitHub
        href: https://github.com/UKRN/OR-demo
      - icon: twitter
        aria-label: Twitter
        href: https://twitter.com/ukrepro
format:
  html:
    theme: [simplex, www/style.scss]
    mainfont: Roboto